<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class BankSeeder extends Seeder
{
	/**
	 * Run the database seeds.
	 *
	 * @return void
	 */
	public function run()
	{
		$data = [
		         ['id' => '4', 'name' => 'Wells Fargo Bank'],
		         ['id' => '5', 'name' => 'Chase Bank'],
		         ['id' => '6', 'name' => 'Bank of America Bank'],
		         ['id' => '7', 'name' => 'Citi Bank'],
		         ['id' => '8', 'name' => 'TD Bank'],
		         ['id' => '9', 'name' => 'Capital One Bank'],
		         ['id' => '10', 'name' => 'Regions Bank'],
		         ['id' => '11', 'name' => 'SunTrust Bank'],
		         ['id' => '12', 'name' => 'BB&T Bank'],
		         ['id' => '13', 'name' => 'US Bank'],
		         ['id' => '14', 'name' => 'Fifth Third Bank'],
		         ['id' => '15', 'name' => 'Citizens Bank'],
		         ['id' => '16', 'name' => 'BBVA Compass Bank'],
		         ['id' => '17', 'name' => 'First National Bank'],
		         ['id' => '18', 'name' => 'First Citizens Bank'],
		         ['id' => '19', 'name' => 'Synuvous Bank'],
		         ['id' => '20', 'name' => 'Commerce Bank'],
		         ['id' => '21', 'name' => 'Bank United Bank'],
		         ['id' => '22', 'name' => 'Sovereign Bank'],
		         ['id' => '23', 'name' => 'Popular Bank'],
		         ['id' => '25', 'name' => '1 First Bank'],
		         ['id' => '26', 'name' => 'Charter Bank '],
		         ['id' => '27', 'name' => 'Wallis State Bank '],
		         ['id' => '28', 'name' => 'iBeriaBank'],
		         ['id' => '29', 'name' => 'Northrim Bank '],
		         ['id' => '30', 'name' => 'The Huntington National Bank '],
		         ['id' => '31', 'name' => 'Affinity Plus Federal Credit Union '],
		         ['id' => '32', 'name' => 'Kinetic Credit Union'],
		         ['id' => '34', 'name' => 'Huntington Bank'],
		         ['id' => '35', 'name' => 'Bank of Walterboro'],
		         ['id' => '36', 'name' => 'TotalBank '],
		         ['id' => '37', 'name' => 'Liberty Bank -Boulder Creek '],
		         ['id' => '38', 'name' => 'Salal Credit Union Bank'],
		         ['id' => '39', 'name' => 'Banc First '],
		         ['id' => '40', 'name' => 'Frost'],
		         ['id' => '41', 'name' => 'Oriental '],
		         ['id' => '42', 'name' => 'First Hawaiian Bank '],
		         ['id' => '43', 'name' => 'National Bank of Arizona'],
		         ['id' => '44', 'name' => 'WoodForest National Bank'],
		         ['id' => '45', 'name' => 'Scotiabank '],
		         ['id' => '46', 'name' => 'State Farm Bank '],
		         ['id' => '47', 'name' => 'Commercial Bank'],
		         ['id' => '48', 'name' => 'RBFCU'],
		         ['id' => '49', 'name' => 'Banco Popular '],
		         ['id' => '50', 'name' => 'FirstMark Credit Union'],
		         ['id' => '51', 'name' => 'PNC Bank '],
		         ['id' => '52', 'name' => 'BMO Harris Bank '],
		         ['id' => '53', 'name' => 'Suncoast Credit Union'],
		         ['id' => '54', 'name' => 'Charles River Bank'],
		         ['id' => '55', 'name' => 'SouthTrust Bank'],
		         ['id' => '56', 'name' => 'South State Bank '],
		         ['id' => '57', 'name' => 'Legacy Bank of Florida'],
		         ['id' => '58', 'name' => 'Centennial Bank'],
		         ['id' => '59', 'name' => ' M & T Bank'],
		         ['id' => '60', 'name' => 'First Federal Savings Bank'],
		         ['id' => '61', 'name' => 'Frontier Bank '],
		         ['id' => '62', 'name' => 'Alpine Bank'],
		         ['id' => '63', 'name' => 'Bank of the West'],
		         ['id' => '64', 'name' => 'Security Service Federal Credit Union'],
		         ['id' => '65', 'name' => 'The Tilden Bank'],
		         ['id' => '66', 'name' => 'Unknown '],
		         ['id' => '67', 'name' => 'Robobank,N.A.'],
		         ['id' => '68', 'name' => 'Santander Bank'],
		         ['id' => '69', 'name' => 'ShareFax Credit Union'],
		         ['id' => '70', 'name' => 'Webster '],
		         ['id' => '71', 'name' => 'Central Valley Community Bank'],
		         ['id' => '72', 'name' => '1st First Commonwealth Bank'],
		         ['id' => '73', 'name' => 'Ocean Bank '],
		         ['id' => '74', 'name' => 'Seacoast National Bank '],
		         ['id' => '75', 'name' => 'Cornerstone Bank '],
		         ['id' => '76', 'name' => 'Royal Bank of Canada'],
		         ['id' => '77', 'name' => 'First Midwest Bank '],
		         ['id' => '78', 'name' => 'Timberland Bank '],
		         ['id' => '79', 'name' => 'Peoples Bank '],
		         ['id' => '80', 'name' => 'UNIFY'],
		         ['id' => '85', 'name' => 'City National Bank '],
		         ['id' => '86', 'name' => 'Key Bank '],
		         ['id' => '87', 'name' => 'WesBanco'],
		         ['id' => '88', 'name' => 'Coleman County State Bank '],
		         ['id' => '89', 'name' => 'Horizon Bank '],
		         ['id' => '90', 'name' => 'VALLIANCE '],
		         ['id' => '91', 'name' => '1st Community Bank '],
		         ['id' => '92', 'name' => 'CNB Bank '],
		         ['id' => '93', 'name' => 'Rockland Trust'],
		         ['id' => '94', 'name' => 'Bank Mutual '],
		         ['id' => '95', 'name' => 'Bank of the Ozarks '],
		         ['id' => '96', 'name' => 'Renasant Bank '],
		         ['id' => '97', 'name' => 'Alliance Bank & Trust '],
		         ['id' => '98', 'name' => 'Embassy Bank '],
		         ['id' => '99', 'name' => 'Torrey Pines Bank'],
		         ['id' => '100', 'name' => 'Pinnacle Express'],
		         ['id' => '101', 'name' => 'envision Financial'],
		         ['id' => '102', 'name' => 'BOFI Federal Bank '],
		         ['id' => '103', 'name' => 'TBD'],
		         ['id' => '104', 'name' => 'Shinhan Bank '],
		         ['id' => '105', 'name' => 'The Bancorp Bank '],
		         ['id' => '106', 'name' => 'Pacific Western Bank'],
		         ['id' => '107', 'name' => 'The Washington Bank '],
		         ['id' => '108', 'name' => 'The Bank of Washington'],
		         ['id' => '109', 'name' => 'East Boston Savings Bank '],
		         ['id' => '110', 'name' => 'BancorpSouth '],
		         ['id' => '111', 'name' => 'PlainsCapitalBank '],
		         ['id' => '112', 'name' => 'AssociatedBank '],
		         ['id' => '113', 'name' => 'Prince Georges  Community Federal Credit Union Bank '],
		         ['id' => '116', 'name' => 'Silicon Valley Bank'],
		         ['id' => '117', 'name' => 'Reliance Bank '],
		         ['id' => '118', 'name' => 'UnionBank'],
		         ['id' => '119', 'name' => 'Webstern Firs '],
		         ['id' => '120', 'name' => 'Platte Valley Bank '],
		         ['id' => '121', 'name' => 'Wadena State bank '],
		         ['id' => '122', 'name' => 'BYLINE BANK '],
		         ['id' => '123', 'name' => 'Enterprise Bank Trust '],
		         ['id' => '124', 'name' => 'Arvest'],
		         ['id' => '125', 'name' => 'Ameris Bank '],
		         ['id' => '126', 'name' => 'Johnson Bank '],
		         ['id' => '127', 'name' => 'FSNB Bank'],
		         ['id' => '128', 'name' => 'Papercity Savings Bank '],
		         ['id' => '129', 'name' => 'Panola National  Bank'],
		         ['id' => '130', 'name' => 'TD Canada Trust '],
		         ['id' => '131', 'name' => 'SunState Federal Credit Union '],
		         ['id' => '132', 'name' => 'Gulf Coast Bank and Trust Company '],
		         ['id' => '133', 'name' => 'KOHO Bank '],
		         ['id' => '134', 'name' => 'Comerica bank '],
		         ['id' => '135', 'name' => 'Woori America Bank'],
		         ['id' => '136', 'name' => 'LAHAVE RIVER CREDIT UNION'],
		         ['id' => '137', 'name' => 'Poppy Bank '],
		         ['id' => '138', 'name' => 'First Community Bank'],
		         ['id' => '139', 'name' => 'United Valley Bank-Hallock'],
		         ['id' => '140', 'name' => '1st Community Federal Credit Union '],
		         ['id' => '141', 'name' => 'Nevada State Bank'],
		         ['id' => '142', 'name' => 'Ascend Federal Credit Union '],
		         ['id' => '143', 'name' => 'Navy Federal Credit Union'],
		         ['id' => '145', 'name' => 'Americas Most Convenient Bank'],
		         ['id' => '146', 'name' => 'BayPort Credit Union'],
		         ['id' => '147', 'name' => 'Business Banking'],
		         ['id' => '148', 'name' => 'VyStar Credit Union '],
		         ['id' => '149', 'name' => 'Great Southern Bank '],
		         ['id' => '150', 'name' => 'Great Western Bank '],
		         ['id' => '151', 'name' => 'Fulton Bank'],
		         ['id' => '152', 'name' => 'McCook National Bank'],
		         ['id' => '153', 'name' => 'Bank of Idaho'],
		         ['id' => '154', 'name' => 'Capital Bank'],
		         ['id' => '155', 'name' => 'Independent Bank '],
		         ['id' => '156', 'name' => 'Texas Citizens Bank '],
		         ['id' => '157', 'name' => 'MECU of Baltimore'],
		         ['id' => '158', 'name' => 'MidWest America Federal Credit Union '],
		         ['id' => '159', 'name' => 'Union '],
		         ['id' => '160', 'name' => 'National Bank of Canada '],
		         ['id' => '161', 'name' => 'Bank of Oklahoma'],
		         ['id' => '162', 'name' => 'CIBC Bank '],
		         ['id' => '163', 'name' => 'Chemical Bank '],
		         ['id' => '164', 'name' => 'Sunstate Bank'],
		         ['id' => '165', 'name' => 'Carolina Alliance Bank '],
		         ['id' => '166', 'name' => 'NewFrontier Bank '],
		         ['id' => '167', 'name' => 'Harborstone Credit Union '],
		         ['id' => '168', 'name' => 'Credit Union of Texas'],
		         ['id' => '169', 'name' => 'Fulton Bank of New Jersey'],
		         ['id' => '170', 'name' => 'Community Bank '],
		         ['id' => '171', 'name' => 'Old Line Bank '],
		         ['id' => '172', 'name' => 'The Bank of Missouri '],
		         ['id' => '173', 'name' => 'First Security Bank '],
		         ['id' => '174', 'name' => 'Summit Credit Union '],
		         ['id' => '175', 'name' => 'First Bank and Trust'],
		         ['id' => '176', 'name' => 'Whitney Bank'],
		         ['id' => '177', 'name' => 'Whitaker Bank'],
		         ['id' => '178', 'name' => 'Northwest Bank '],
		         ['id' => '180', 'name' => 'SPACE COAST CREDIT UNION'],
		         ['id' => '182', 'name' => 'Teachers Credit Union'],
		         ['id' => '183', 'name' => 'Laurentian Bank'],
		         ['id' => '184', 'name' => 'Green Bank'],
		         ['id' => '185', 'name' => 'Crossfirst Bank'],
		         ['id' => '186', 'name' => 'First Tennessee'],
		         ['id' => '187', 'name' => 'UMB BANK'],
		         ['id' => '188', 'name' => 'Industrial Bank'],
		         ['id' => '189', 'name' => 'OPUS BANK'],
		         ['id' => '190', 'name' => 'Eastern Bank'],
		         ['id' => '191', 'name' => 'Glacier Family of Banks'],
		         ['id' => '192', 'name' => 'Zions Bank'],
		         ['id' => '193', 'name' => 'The Middlefield Banking Company'],
		         ['id' => '194', 'name' => 'Credit Union of Southern California'],
		         ['id' => '195', 'name' => 'TCF BANK'],
		         ['id' => '196', 'name' => 'Florida Community Bank'],
		         ['id' => '197', 'name' => 'Bridge Bank'],
		         ['id' => '198', 'name' => 'Freedom Bank '],
		         ['id' => '199', 'name' => 'GECU'],
		         ['id' => '200', 'name' => 'Simple'],
		         ['id' => '201', 'name' => 'Mid America Bank'],
		         ['id' => '202', 'name' => 'First Merchants Bank'],
		         ['id' => '203', 'name' => 'Uwharrie Bank'],
		         ['id' => '204', 'name' => 'University Federal Credit Union'],
		         ['id' => '205', 'name' => 'First Atlantic '],
		         ['id' => '206', 'name' => 'PROGRESSIVE SAVINGS BANK'],
		         ['id' => '207', 'name' => 'Farmers and Merchants Bank'],
		         ['id' => '208', 'name' => 'Kennebec Savings Bank'],
		         ['id' => '209', 'name' => 'MVB'],
		         ['id' => '210', 'name' => 'Ponce Bank'],
		         ['id' => '211', 'name' => 'BMO Bank of Montreal'],
		         ['id' => '212', 'name' => 'Central Bank'],
		         ['id' => '213', 'name' => 'Center State'],
		         ['id' => '214', 'name' => 'One United Bank'],
		         ['id' => '215', 'name' => 'Security State Bank'],
		         ['id' => '216', 'name' => 'US Century Bank'],
		         ['id' => '217', 'name' => 'Institution for Savings'],
		         ['id' => '218', 'name' => 'Midland'],
		         ['id' => '219', 'name' => 'MB Financial'],
		         ['id' => '220', 'name' => 'Frederick County Bank (FCB)'],
		         ['id' => '221', 'name' => 'Pacific Premier Bank'],
		         ['id' => '222', 'name' => 'Pinnacle Bank'],
		         ['id' => '223', 'name' => 'North East Community Bank'],
		         ['id' => '224', 'name' => 'Black Hills Federal Credit Union'],
		         ['id' => '225', 'name' => 'Old National Bank'],
		         ['id' => '226', 'name' => 'Wood & Huston Bank '],
		         ['id' => '227', 'name' => '4 Front Credit Union'],
		         ['id' => '228', 'name' => 'Intercontinental Bank'],];
		
		DB::table('banks')->insert($data);
	}
}
