<?php

namespace Tests;

use App\User;
use Faker\Factory as Faker;
use Illuminate\Foundation\Testing\DatabaseMigrations;
use Illuminate\Foundation\Testing\TestCase as BaseTestCase;

/**
 * Class TestCase.
 */
abstract class TestCase extends BaseTestCase
{
    use CreatesApplication, DatabaseMigrations;

    protected $faker;

    /**
     * Set Up.
     */
    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->faker = Faker::create();
        $this->artisan('passport:install');
        $this->artisan('storage:link');
        $this->seed();
    }

    /**
     * Tear Down.
     */
    public function tearDown()
    {
        $this->artisan('migrate:reset');
        parent::tearDown(); // TODO: Change the autogenerated stub
    }

    /**
     * Return request headers needed to interact with the API.
     *
     * @return array of headers
     */
    public function headers()
    {
        $user = factory(User::class)->create();

        $token = $user->createToken('Token Name')->accessToken;

        return $headers = ['Authorization' => 'Bearer '.$token];
    }

    public function admin()
    {
        $user = factory(User::class)->create();

        //ingresar el role aca

        $token = $user->createToken($user->email)->accessToken;

        return $headers = ['Authorization' => 'Bearer '.$token];
    }
}
